name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies
        run: |
          pip install markdown jinja2
          
      - name: Build
        run: |
          make

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: html
          single-commit: true
          commit-message: Auto-deploy
          clean: true
          clean-exclude: |
            docs/
